function ColorMyPencils(color)
    color = color or "srcery"
    vim.cmd.colorscheme(color)

    vim.api.nvim_set_hl(0, "Normal",  { bg = "none"})
    vim.api.nvim_set_hl(0, "NormalFloat",  { bg = "none"})

    vim.api.nvim_set_hl(0, "StatusLineDef",             {ctermfg = "LightGrey", ctermbg = "Black", fg = "#FCE8C3", bg = "#1C1B19"})
    vim.api.nvim_set_hl(0, "ModeNormal",                {ctermfg = "Black", ctermbg = "Green", fg = "#1C1B19", bg = "#519F50", bold = true})
    vim.api.nvim_set_hl(0, "ModeInsert",                {ctermfg = "Black", ctermbg = "White", fg = "#1C1B19", bg = "#BAA67F", bold = true})
    vim.api.nvim_set_hl(0, "ModeReplace",               {ctermfg = "Black", ctermbg = "Red", fg = "#1C1B19", bg = "#F75341", bold = true})
    vim.api.nvim_set_hl(0, "ModeVisual",                {ctermfg = "Black", ctermbg = "LightBlue", fg = "#1C1B19", bg = "#68A8E4", bold = true})
    vim.api.nvim_set_hl(0, "ModeVisual-Block",          {ctermfg = "LightGrey", ctermbg = "Blue", fg = "#FCE8C3", bg = "#2C78BF", bold = true})
    vim.api.nvim_set_hl(0, "ModeCommand",               {ctermfg = "Black", ctermbg = "Yellow", fg = "#1C1B19", bg = "#FBB829", bold = true})
    vim.api.nvim_set_hl(0, "ModeSelect",                {ctermfg = "LightGrey", ctermbg = "Magenta", fg = "#FCE8C3", bg = "#E02C6D", bold = true})
    vim.api.nvim_set_hl(0, "ModeNormalToGitSep",        {ctermfg = "Green", ctermbg = "Red", fg = "#519F50", bg = "#D75F00"})
    vim.api.nvim_set_hl(0, "ModeInsertToGitSep",        {ctermfg = "White", ctermbg = "Red", fg = "#BAA67F", bg = "#D75F00"})
    vim.api.nvim_set_hl(0, "ModeReplaceToGitSep",       {ctermfg = "Red", ctermbg = "Red", fg = "#F75341", bg = "#D75F00"})
    vim.api.nvim_set_hl(0, "ModeVisualToGitSep",        {ctermfg = "LightBlue", ctermbg = "Red", fg = "#68A8E4", bg = "#D75F00"})
    vim.api.nvim_set_hl(0, "ModeVisual-BlockToGitSep",  {ctermfg = "Blue", ctermbg = "Red", fg = "#2C78BF", bg = "#D75F00"})
    vim.api.nvim_set_hl(0, "ModeCommandToGitSep",       {ctermfg = "Yellow", ctermbg = "Red", fg = "#FBB829", bg = "#D75F00"})
    vim.api.nvim_set_hl(0, "ModeSelectToGitSep",        {ctermfg = "Magenta", ctermbg = "Red", fg = "#E02C6D", bg = "#D75F00"})
    vim.api.nvim_set_hl(0, "Git",                       {ctermfg = "LightGrey", ctermbg = "Red", fg = "#FCE8C3", bg = "#D75F00"})
    vim.api.nvim_set_hl(0, "GitToNormSep",              {ctermfg = "Red", ctermbg = "Black", fg = "#D75F00", bg = "#1C1B19"})
    vim.api.nvim_set_hl(0, "Normalhl",                  {ctermfg = "LightGrey", ctermbg = "Black", fg = "#FCE8C3", bg = "#1C1B19"})
    vim.api.nvim_set_hl(0, "NormToTypeSep",             {ctermfg = "Blue", ctermbg = "None", fg = "#2C78BF", bg = "none"})
    vim.api.nvim_set_hl(0, "Filetype",                  {ctermfg = "LightGrey", ctermbg = "Blue", fg = "#FCE8C3", bg = "#2C78BF"})
    vim.api.nvim_set_hl(0, "TypeToRowColSep",           {ctermfg = "Green", ctermbg = "Blue", fg = "#519F50", bg = "#2C78BF"})
    vim.api.nvim_set_hl(0, "RowCol",                    {ctermfg = "Black", ctermbg = "Green", fg = "#1C1B19", bg = "#519F50"})
    vim.api.nvim_set_hl(0, "StatusLineExtra",           {ctermfg = "Black", ctermbg = "Green", fg = "#1C1B19", bg = "#519F50"})
end

ColorMyPencils()
